# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# compile CXX with /usr/bin/c++
CXX_FLAGS = -O3 -DNDEBUG -I/home/human/Desktop/HeadPose/head_pose_estimation/demo/. -I/home/human/Desktop/HeadPose/head_pose_estimation/demo/.. -I/usr/include/ni -I/home/human/Desktop/opencv-2.4.7/include   

CXX_DEFINES = 

